# Generated by Django 4.2 on 2023-04-29 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0002_alter_person_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
