# Generated by Django 4.2 on 2023-04-29 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedigree', '0004_family_family_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='family',
            name='family_member',
        ),
    ]
